name: pkm_lucky_draw
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.2
  flutter_secure_storage: ^9.2.4
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/pokedex/
    - images/pokedex/hires/
    - images/pokedex/sprites/
